name: .NET 8

on:
    push:
        branches: ["main", "develop"]
    pull_request:
        branches: ["main", "develop"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET 8
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"
            - name: Restore dependencies
              run: dotnet restore "src/backend/ExamSystem.sln"
            - name: Build
              run: dotnet build "src/backend/ExamSystem.sln" --configuration Release --no-restore
        # - name: Test
        #  run: dotnet test "src/ExamSystem.sln" --no-restore --verbosity normal
